Repository dreamyPatisiel/devdevdev-client, pull requests merged in 2024-02, with the labels that each got.

#7 [ DP-36] Zustand를 사용한 모달 상태관리
  _tests_/loginBtn.test.tsx
  components/LoginButton.tsx
  components/header.tsx
  components/layout.tsx
  components/modal.tsx
  package.json
  pages/index.tsx
  pages/login/LoginButton.tsx
  pages/login/index.tsx
  pnpm-lock.yaml
  store/modalStore.ts
Labels: features

#10 [DP-100] 드롭다운 메뉴아이템 로직 수정
  components/dropdown.tsx
  pages/pickpickpick/index.page.tsx
Labels: fix

#12 [DP-102] 모달 컴포넌트 구현
  _tests_/loginbtn.test.tsx
  components/LoginButton.tsx
  components/buttons/subButton.tsx
  components/header.tsx
  components/layout.tsx
  components/modal.tsx
  components/modals/modal.tsx
  components/modals/modalVariants.ts
  pages/index.page.tsx
  store/modalStore.ts
Labels: enhancement

#11 [DP-88] 픽픽픽 작성 페이지 UI 구현
  components/buttons/mainButtons.tsx
  components/validationMessage.tsx
  package.json
  pages/pickpickpick/index.page.tsx
  pages/pickposting/components/MarkdownEditor.tsx
  pages/pickposting/components/PickPostCard.tsx
  pages/pickposting/index.page.tsx
  pnpm-lock.yaml
  public/image/arrow-left.svg
  public/image/exclamation-circle.svg
  public/image/images.svg
  public/image/pencil-alt.svg
  styles/globals.css
Labels: enhancement

#13 [DP-103] import 정렬 추가
  .prettierrc
  _tests_/Test.test.tsx
  _tests_/loginbtn.test.tsx
  _tests_/mocks/browser.ts
  _tests_/mocks/handlers/login.ts
  _tests_/mocks/handlers/picpickpick.ts
  _tests_/mocks/server.ts
  api/useSetAxiosConfig.tsx
  components/LoginButton.tsx
  components/buttons/mainButtons.tsx
  components/dropdown.tsx
  components/header.tsx
  components/layout.tsx
  components/modals/modal.tsx
  components/searchInput.tsx
  components/validationMessage.tsx
  core/baseInstance.ts
  jest.config.js
  package.json
  pages/_app.page.tsx
  pages/pickpickpick/api/useInfinitePickData.ts
  pages/pickpickpick/components/PickContainer.tsx
  pages/pickpickpick/index.page.tsx
  pages/pickposting/components/MarkdownEditor.tsx
  pages/pickposting/index.page.tsx
  pages/techblog/components/techCard.tsx
  pages/techblog/index.page.tsx
  pnpm-lock.yaml
  stores/loginStore.ts
  stores/modalStore.ts
  tsconfig.json
Labels: fix
